web:
  image: 'gitlab/gitlab-ce:latest'
  container_name: gitlab-docker
  restart: always
  hostname: 'gitlab.f5se.io'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      letsencrypt['enable'] = true
      external_url 'https://gitlab.f5se.io'
      letsencrypt['contact_emails'] = ['a.zong@f5.com']
      letsencrypt['auto_renew'] = false
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
   # uncomment it and rerun ./compose.sh to make gitlab listen to 80.
   # This can leverage letsencrypt automation tools to apply DV certificates.
   # More details about https setup, see: 
   #  https://docs.gitlab.com/omnibus/settings/nginx.html#enable-https
   #- 80:80  
   - 443:443
   - '8022:22'
  volumes:
    - ${HOMEDIR}/srv/gitlab/config:/etc/gitlab
    - ${HOMEDIR}/srv/gitlab/logs:/var/log/gitlab
    - ${HOMEDIR}/srv/gitlab/data:/var/opt/gitlab

